# Generated by Django 5.2.12 on 2026-07-21 23:45

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUserPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Προσαρμοσμένο Δικαίωμα Χρήστη',
                'verbose_name_plural': 'Προσαρμοσμένα Δικαιώματα Χρήστη',
                'permissions': (('is_secretariat', 'Is a secretariat user'),),
            },
        ),
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, null=True)),
                ('given_name', models.CharField(max_length=50)),
                ('given_name_en', models.CharField(max_length=50, null=True)),
                ('surname', models.CharField(max_length=70)),
                ('surname_en', models.CharField(max_length=70, null=True)),
                ('display_name', models.CharField(blank=True, max_length=150, null=True)),
                ('display_name_en', models.CharField(blank=True, max_length=150, null=True)),
                ('display_name_full', models.CharField(blank=True, max_length=200, null=True)),
                ('is_internal', models.BooleanField(default=True, null=True)),
                ('institution', models.CharField(blank=True, max_length=100, null=True)),
                ('school', models.CharField(blank=True, max_length=100, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('title', models.CharField(max_length=200, null=True)),
                ('can_apply_for_phd', models.BooleanField(default=False, null=True)),
                ('can_review_phd_apps', models.BooleanField(default=True, null=True)),
                ('can_post_theses', models.BooleanField(default=True, null=True)),
            ],
            options={
                'verbose_name': 'Μέλος Προσωπικού',
                'verbose_name_plural': 'Μέλη Προσωπικού',
                'ordering': ['pk'],
            },
            bases=(core.models.PersonStrMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('given_name', models.CharField(max_length=200, null=True)),
                ('surname', models.CharField(max_length=200, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('secondary_email', models.EmailField(max_length=254, null=True)),
                ('fathers_name', models.CharField(blank=True, max_length=50, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('tin', models.CharField(blank=True, max_length=50, null=True)),
                ('ssn', models.CharField(blank=True, max_length=50, null=True)),
                ('gender', models.CharField(choices=[('M', 'Άρρεν'), ('F', 'Θήλυ'), ('O', 'Άλλο')], max_length=1, null=True)),
                ('home_address_street', models.CharField(blank=True, max_length=70, null=True)),
                ('home_address_no', models.IntegerField(blank=True, null=True)),
                ('home_address_po_box', models.CharField(blank=True, max_length=30, null=True)),
                ('home_address_city', models.CharField(blank=True, max_length=70, null=True)),
                ('home_address_country', models.CharField(blank=True, default='Ελλάδα', max_length=70, null=True)),
                ('mobile_phone', models.CharField(blank=True, max_length=30, null=True)),
                ('home_phone', models.CharField(blank=True, max_length=30, null=True)),
                ('work_address_street', models.CharField(default='Ομήρου', max_length=70, null=True)),
                ('work_address_no', models.CharField(default='9', max_length=10, null=True)),
                ('work_address_po_box', models.CharField(default='17778', max_length=30, null=True)),
                ('work_address_city', models.CharField(default='Αθήνα', max_length=70, null=True)),
                ('work_address_country', models.CharField(default='Ελλάδα', max_length=70, null=True)),
                ('work_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('pic', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Προσωπικά Στοιχεία',
                'verbose_name_plural': 'Προσωπικά Στοιχεία',
                'ordering': ['pk'],
            },
        ),
    ]
