# Generated by Django 5.2.12 on 2026-08-05 21:27

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUserPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Προσαρμοσμένο Δικαίωμα Χρήστη',
                'verbose_name_plural': 'Προσαρμοσμένα Δικαιώματα Χρήστη',
                'permissions': (('is_secretariat', 'Is a secretariat user'),),
            },
        ),
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='Email')),
                ('given_name', models.CharField(max_length=50, verbose_name='Όνομα')),
                ('given_name_en', models.CharField(max_length=50, null=True, verbose_name='Όνομα (Αγγλικά)')),
                ('surname', models.CharField(max_length=70, verbose_name='Επώνυμο')),
                ('surname_en', models.CharField(max_length=70, null=True, verbose_name='Επώνυμο (Αγγλικά)')),
                ('display_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Ονοματεπώνυμο')),
                ('display_name_en', models.CharField(blank=True, max_length=150, null=True, verbose_name='Ονοματεπώνυμο (Αγγλικά)')),
                ('display_name_full', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ονοματεπώνυμο και Ιδιότητα')),
                ('is_internal', models.BooleanField(default=True, null=True, verbose_name='Εσωτερικός Χρήστης')),
                ('institution', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ίδρυμα')),
                ('school', models.CharField(blank=True, max_length=100, null=True, verbose_name='Σχολή')),
                ('department', models.CharField(blank=True, max_length=100, null=True, verbose_name='Τμήμα')),
                ('title', models.CharField(max_length=200, null=True, verbose_name='Ιδιότητα')),
                ('can_apply_for_phd', models.BooleanField(default=False, null=True, verbose_name='Δυνατότητα υποβολής αίτησης για διδακτορικό')),
                ('can_review_phd_apps', models.BooleanField(default=True, null=True, verbose_name='Δυνατότητα αξιολόγησης αιτήσεων για διδακτορικό')),
                ('can_post_theses', models.BooleanField(default=True, null=True, verbose_name='Δυνατότητα δημοσίευσης διατριβών')),
            ],
            options={
                'verbose_name': 'Μέλος Προσωπικού',
                'verbose_name_plural': 'Μέλη Προσωπικού',
                'ordering': ['pk'],
            },
            bases=(core.models.PersonStrMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='Δημιουργήθηκε στις')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Ενημερώθηκε στις')),
                ('given_name', models.CharField(max_length=200, null=True, verbose_name='Όνομα')),
                ('surname', models.CharField(max_length=200, null=True, verbose_name='Επώνυμο')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='Email')),
                ('secondary_email', models.EmailField(max_length=254, null=True, verbose_name='Δεύτερο Email')),
                ('fathers_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Όνομα Πατέρα')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Ημ/νία Γέννησης')),
                ('tin', models.CharField(blank=True, max_length=50, null=True, verbose_name='ΑΦΜ')),
                ('ssn', models.CharField(blank=True, max_length=50, null=True, verbose_name='ΑΜΚΑ')),
                ('gender', models.CharField(choices=[('M', 'Άρρεν'), ('F', 'Θήλυ'), ('O', 'Άλλο')], max_length=1, null=True, verbose_name='Φύλο')),
                ('home_address_street', models.CharField(blank=True, max_length=70, null=True, verbose_name='Οδός Κατοικίας')),
                ('home_address_no', models.IntegerField(blank=True, null=True, verbose_name='Αριθμός Κατοικίας')),
                ('home_address_po_box', models.CharField(blank=True, max_length=30, null=True, verbose_name='Τ.Κ. Κατοικίας')),
                ('home_address_city', models.CharField(blank=True, max_length=70, null=True, verbose_name='Πόλη Κατοικίας')),
                ('home_address_country', models.CharField(blank=True, default='Ελλάδα', max_length=70, null=True, verbose_name='Χώρα Κατοικίας')),
                ('mobile_phone', models.CharField(blank=True, max_length=30, null=True, verbose_name='Κινητό Τηλέφωνο')),
                ('home_phone', models.CharField(blank=True, max_length=30, null=True, verbose_name='Τηλέφωνο Κατοικίας')),
                ('work_address_street', models.CharField(default='Ομήρου', max_length=70, null=True, verbose_name='Οδός Εργασίας')),
                ('work_address_no', models.CharField(default='9', max_length=10, null=True, verbose_name='Αριθμός Εργασίας')),
                ('work_address_po_box', models.CharField(default='17778', max_length=30, null=True, verbose_name='Τ.Κ. Εργασίας')),
                ('work_address_city', models.CharField(default='Αθήνα', max_length=70, null=True, verbose_name='Πόλη Εργασίας')),
                ('work_address_country', models.CharField(default='Ελλάδα', max_length=70, null=True, verbose_name='Χώρα Εργασίας')),
                ('work_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Τηλέφωνο Εργασίας')),
                ('pic', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Εικόνα')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Δημιουργήθηκε από')),
            ],
            options={
                'verbose_name': 'Προσωπικά Στοιχεία',
                'verbose_name_plural': 'Προσωπικά Στοιχεία',
                'ordering': ['pk'],
            },
        ),
    ]
