# Generated by Django 5.2.12 on 2026-08-05 21:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('curricula', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='curricula.department', verbose_name='Τμήμα'),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='curricula.studyprogram', verbose_name='Πρόγραμμα Σπουδών'),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Ενημερώθηκε από'),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Χρήστης'),
        ),
        migrations.AddField(
            model_name='staffmember',
            name='internal_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='curricula.department', verbose_name='Εσωτερικό Τμήμα'),
        ),
        migrations.AddField(
            model_name='staffmember',
            name='personal_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.personalinfo', verbose_name='Προσωπικά Στοιχεία'),
        ),
        migrations.AddField(
            model_name='staffmember',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Χρήστης'),
        ),
    ]
