# Generated by Django 5.2.12 on 2026-04-02 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('bodies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_and_time', models.DateTimeField()),
                ('location', models.CharField(default='Ομήρου 9, 17778, Αθήνα, Ελλάδα', max_length=30)),
                ('notes', models.TextField(blank=True, null=True)),
                ('index', models.IntegerField()),
                ('absent', models.ManyToManyField(blank=True, related_name='meeting_absent', to='accounts.staffmember')),
                ('collective_body', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bodies.collectivebody')),
                ('present', models.ManyToManyField(blank=True, related_name='meeting_present', to='accounts.staffmember')),
            ],
        ),
    ]
