# Generated by Django 5.2.12 on 2026-07-28 14:17

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('bodies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('index', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('location', models.CharField(default='Ομήρου 9, 17778, Αθήνα, Ελλάδα', max_length=30)),
                ('date_and_time', models.DateTimeField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('absent', models.ManyToManyField(blank=True, related_name='meeting_absent', to='accounts.staffmember')),
                ('collective_body', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bodies.collectivebody')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('present', models.ManyToManyField(blank=True, related_name='meeting_present', to='accounts.staffmember')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Συνεδρίαση',
                'verbose_name_plural': 'Συνεδριάσεις',
                'ordering': ['pk'],
            },
        ),
    ]
