# Generated by Django 5.2.12 on 2026-08-22 13:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subjects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='Δημιουργήθηκε στις')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Ενημερώθηκε στις')),
                ('request_subject', models.CharField(max_length=100, verbose_name='Θέμα Αιτήματος')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Περιγραφή')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bodyapplications', to=settings.AUTH_USER_MODEL, verbose_name='Αιτών')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Δημιουργήθηκε από')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='subjects.subject', verbose_name='Θέμα')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Ενημερώθηκε από')),
            ],
            options={
                'verbose_name': 'Αίτηση',
                'verbose_name_plural': 'Αιτήσεις',
                'ordering': ['pk'],
            },
        ),
    ]
