# Generated by Django 5.2.12 on 2026-08-22 13:18

import core.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bodies', '0001_initial'),
        ('curricula', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='Δημιουργήθηκε στις')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Ενημερώθηκε στις')),
                ('index', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Θέση')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Σημειώσεις')),
                ('applicant_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Αιτών')),
                ('collective_body', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bodies.collectivebody', verbose_name='Συλλογικό Όργανο')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Δημιουργήθηκε από')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='curricula.department', verbose_name='Τμήμα')),
                ('program', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='curricula.studyprogram', verbose_name='Πρόγραμμα Σπουδών')),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='curricula.school', verbose_name='Σχολή')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Ενημερώθηκε από')),
            ],
            options={
                'verbose_name': 'Θέμα',
                'verbose_name_plural': 'Θέματα',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='Δημιουργήθηκε στις')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Ενημερώθηκε στις')),
                ('title', models.CharField(choices=[('Approval', 'Έγκριση ✔'), ('Rejection', 'Απόρριψη ❌'), ('Pending', 'Σε εκκρεμότητα ⏳')], max_length=10, verbose_name='Τελική Απόφαση')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Δημιουργήθηκε από')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Ενημερώθηκε από')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='decision', to='subjects.subject', verbose_name='Θέμα')),
            ],
            options={
                'verbose_name': 'Απόφαση',
                'verbose_name_plural': 'Αποφάσεις',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='SubjectCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='Δημιουργήθηκε στις')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Ενημερώθηκε στις')),
                ('title_gr', models.CharField(max_length=100, verbose_name='Τίτλος (Ελληνικά)')),
                ('title_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='Τίτλος (Αγγλικά)')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Δημιουργήθηκε από')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Ενημερώθηκε από')),
            ],
            options={
                'verbose_name': 'Κατηγορία Θέματος',
                'verbose_name_plural': 'Κατηγορίες Θεμάτων',
                'ordering': ['pk'],
            },
            bases=(core.models.TitleStrMixin, models.Model),
        ),
        migrations.AddField(
            model_name='subject',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='subjects.subjectcategory', verbose_name='Κατηγορία'),
        ),
        migrations.CreateModel(
            name='SubjectType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='Δημιουργήθηκε στις')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Ενημερώθηκε στις')),
                ('title_gr', models.CharField(max_length=100, verbose_name='Τίτλος (Ελληνικά)')),
                ('title_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='Τίτλος (Αγγλικά)')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Δημιουργήθηκε από')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Ενημερώθηκε από')),
            ],
            options={
                'verbose_name': 'Τύπος Θέματος',
                'verbose_name_plural': 'Τύποι Θεμάτων',
                'ordering': ['pk'],
            },
            bases=(core.models.TitleStrMixin, models.Model),
        ),
        migrations.AddField(
            model_name='subject',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='subjects.subjecttype', verbose_name='Τύπος'),
        ),
    ]
