# Generated by Django 5.2.12 on 2026-04-02 17:33

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_gr', models.CharField(max_length=100)),
                ('title_en', models.CharField(max_length=100)),
                ('short_gr', models.CharField(blank=True, max_length=20, null=True)),
                ('short_en', models.CharField(blank=True, max_length=20, null=True)),
                ('code_gr', models.CharField(blank=True, max_length=20, null=True)),
                ('code_en', models.CharField(blank=True, max_length=20, null=True)),
            ],
            bases=(core.models.TitleStrMixin, models.Model),
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_gr', models.CharField(max_length=100)),
                ('title_en', models.CharField(max_length=100)),
                ('short_gr', models.CharField(blank=True, max_length=20, null=True)),
                ('short_en', models.CharField(blank=True, max_length=20, null=True)),
                ('code_gr', models.CharField(blank=True, max_length=20, null=True)),
                ('code_en', models.CharField(blank=True, max_length=20, null=True)),
                ('institution', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='curricula.institution')),
            ],
            bases=(core.models.TitleStrMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_gr', models.CharField(max_length=100)),
                ('title_en', models.CharField(max_length=100)),
                ('short_gr', models.CharField(blank=True, max_length=20, null=True)),
                ('short_en', models.CharField(blank=True, max_length=20, null=True)),
                ('code_gr', models.CharField(blank=True, max_length=20, null=True)),
                ('code_en', models.CharField(blank=True, max_length=20, null=True)),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='curricula.school')),
            ],
            options={
                'abstract': False,
            },
            bases=(core.models.TitleStrMixin, models.Model),
        ),
        migrations.CreateModel(
            name='StudyProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_gr', models.CharField(max_length=100)),
                ('title_en', models.CharField(max_length=100, null=True)),
                ('short_gr', models.CharField(blank=True, max_length=20, null=True)),
                ('short_en', models.CharField(blank=True, max_length=20, null=True)),
                ('code_gr', models.CharField(blank=True, max_length=20, null=True)),
                ('code_en', models.CharField(blank=True, max_length=20, null=True)),
                ('type', models.CharField(choices=[('Προπτυχιακό', 'Προπτυχιακό'), ('Μεταπτυχιακό', 'Μεταπτυχιακό'), ('Διδακτορικό', 'Διδακτορικό'), ('Μεταδιδακτορικό', 'Μεταδιδακτορικό'), ('´Άλλο', '´Άλλο')], max_length=100)),
                ('sis_code', models.CharField(blank=True, choices=[('550', 'Προπτυχιακό'), ('1550', 'ΠΜΣ Πληροφορική και Τηλεματική'), ('1556', 'ΠΜΣ Εφαρμοσμένη Πληροφορική'), ('1557', 'ΠΜΣ Επιστήμη των Υπολογιστών και Πληροφορική'), ('1560', 'Προηγμένες Τεχνολογίες Πληροφορικής και Εφαρμογές')], null=True)),
                ('active', models.BooleanField(default=True, null=True)),
                ('has_thesis', models.BooleanField(default=True, null=True)),
                ('thesis_semesters', models.IntegerField(default=2, null=True)),
                ('thesis_report_semesters', models.IntegerField(default=1, null=True)),
                ('thesis_has_report', models.BooleanField(default=False, null=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='curricula.department')),
            ],
            options={
                'abstract': False,
            },
            bases=(core.models.TitleStrMixin, models.Model),
        ),
    ]
