"""
Django settings for hua_cbms project.

Generated by 'django-admin startproject' using Django 5.2.12.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from django_auth_ldap.config import LDAPSearch
import ldap
import os

from accounts import emails

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-^n3wa82vhfu)z!y79a8rkerj&h)=&x+t9=&muhg#22u*c8p%us'

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = os.environ.get('DEBUG') == 'True'
# DUMMY_EMAILS = os.environ.get('DUMMY_EMAILS') == 'True'
DEBUG = True
DUMMY_EMAILS = True

if DUMMY_EMAILS:
    print('Outputting email messages to console because env variable DUMMY_EMAILS is set to True.')

ALLOWED_HOSTS = ['localhost', '127.0.0.1']
CSRF_TRUSTED_ORIGINS = ['https://mydep.ditapps.hua.gr', 'https://myfaculty-dev.ditapps.hua.gr', 'http://localhost:8080',
                        'http://127.0.0.1:8080']

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
MEDIA_TMP_EXPORT = BASE_DIR / 'media/export/tmp'

if not os.path.isdir(MEDIA_TMP_EXPORT):
    os.makedirs(MEDIA_TMP_EXPORT)

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'static'

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

# Application definition

INSTALLED_APPS = [
    'django_extensions',
    'dal',
    'dal_select2',
    'hua_cbms.apps.HuaAdminSiteConfig', # replaces django.contrib.admin, because a custom AdminSite is used
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'crispy_forms',
    'crispy_bootstrap5',
    'rest_framework',
    'rest_framework.authtoken',
    # 'django_recaptcha',
    'django_celery_results',
    'accounts',
    'api',
    'attachments',
    'bodies',
    'bodyapplications',
    'core',
    'curricula',
    'meetings',
    'scopes',
    'subjects'
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication'
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAdminUser'
    ],
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'accounts.middleware.DevServerMiddleware'
]

ROOT_URLCONF = 'hua_cbms.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',  # Available only when DEBUG=True
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'hua_cbms.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'hua_cbms',  # os.environ.get('POSTGRES_NAME'),
        'USER': 'hua_cbms',  # os.environ.get('POSTGRES_USER'),
        'PASSWORD': 'hua_cbms',  # os.environ.get('POSTGRES_PASSWORD'),
        'HOST': '127.0.0.1',  # os.environ.get('POSTGRES_HOST'),
        'PORT': '5432',  # os.environ.get('POSTGRES_PORT'),

    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTHENTICATION_BACKENDS = [
    "django_auth_ldap.backend.LDAPBackend",
    "hua_cbms.auth.CustomAuthBackend",
    "django.contrib.auth.backends.ModelBackend",
]

LOGIN_REDIRECT_URL = '/'

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'el'

TIME_ZONE = 'Europe/Athens'

USE_I18N = True
USE_TZ = True

LANGUAGES = [
    ("el", "Ελληνικά"),
    ("en", "English"),
]

LOCALE_PATHS = [
    BASE_DIR / "locale",
]

# USE_L10N = False

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

DATE_FORMAT = '%d/%m/%Y'
DATE_INPUT_FORMATS = ['%d/%m/%Y']
DATETIME_FORMAT = '%d/%m/%Y %H:%M'
DATETIME_INPUT_FORMATS = ['%d/%m/%Y %H:%M']

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{asctime} {levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
        'file': {
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'django_app.log',  # access gets denied at /var/log/
            'formatter': 'verbose'
        }
    },
    'loggers': {
        'django_auth_ldap': {
            'level': 'DEBUG',
            'handlers': ['file', 'console']
        },
        'hua_cbms': {
            'level': 'DEBUG',
            'handlers': ['file', 'console'],
        }
    }
}

# LDAP options
# AUTH_LDAP_SERVER_URI = os.environ.get('AUTH_LDAP_SERVER_URI')
# AUTH_LDAP_BIND_DN = os.environ.get('AUTH_LDAP_BIND_DN')
# AUTH_LDAP_BIND_PASSWORD = os.environ.get('AUTH_LDAP_BIND_PASSWORD')
# AUTH_LDAP_SERVER_URI = "ldap://10.100.51.117"
AUTH_LDAP_SERVER_URI = "ldap://ldap3.ditapps.hua.gr"
AUTH_LDAP_BIND_DN = "uid=it2022057,ou=People,dc=hua,dc=gr"
AUTH_LDAP_BIND_PASSWORD = "go&U2E5$U$"
AUTH_LDAP_USER_SEARCH = LDAPSearch(
    "dc=hua,dc=gr",
    ldap.SCOPE_SUBTREE,
    "(uid=%(user)s)"
)
AUTH_LDAP_USER_ATTR_MAP = {
    "first_name": "givenName",
    "last_name": "sn",
    "email": "email"
}
# AUTH_LDAP_START_TLS = os.getenv('AUTH_LDAP_START_TLS') == 'True'
AUTH_LDAP_START_TLS = True
AUTH_LDAP_GLOBAL_OPTIONS = {
    ldap.OPT_X_TLS_REQUIRE_CERT: ldap.OPT_X_TLS_NEVER
}

# Custom auth backend
INTERNAL_DOMAIN = 'hua.gr'

# docx templates
ECTS_GR_TEMPLATE = 'ects_gr'
ECTS_EN_TEMPLATE = 'ects_en'
PROPOSAL_TEMPLATE = 'proposal'
LEAVE_TEMPLATE = 'leave_template'
PHD_APPLICATION_TEMPLATE = 'phdapplication'

# Mailer settings
ALWAYS_NOTIFY = 'byronlouki21@gmail.com, b.loukidelis@gmail.com'
DEAN_EMAIL = 'it2022057@hua.gr'
# ALWAYS_NOTIFY = 'ditdean@hua.gr,itsec@hua.gr'
# DEAN_EMAIL = 'thkam@hua.gr'
EMAIL_PLATFORM_URL = 'https://mydep.ditapps.hua.gr'

# SIS settings
SIS_KEYCLOAK_TOKEN_URL = os.environ.get('SIS_KEYCLOAK_TOKEN_URL')
SIS_CLIENT_ID = os.environ.get('SIS_CLIENT_ID')
SIS_USER_NAME = os.environ.get('SIS_USER_NAME')
SIS_PASSWD = os.environ.get('SIS_PASSWD')

# Password complexity for user signup
UPPERCASE_MIN = 1
LOWERCASE_MIN = 1
DIGITS_MIN = 1
SPECIAL_CHARACTERS_MIN = 2
MIN_LENGTH = 8
# PASSWORD_SPECIAL_CHARS = r'[!@#\$%\^&\*\(\)_\+\-=\[\]\{\};:\"",\.<>\/\?\\\|~]'
PASSWORD_SPECIAL_CHARS = '{}!@#$%^&*()-+'

# User registration options
MAX_AGE = 32000 # number seconds one time registration links are active
REGISTRATION_MESSAGE = emails.USER_REGISTRATION_MESSAGE
REGISTRATION_SUBJECT = 'Activate your account / Ενεργοποιήση του Λογαριασμού σας'

FORGOT_PASSWORD_BODY = emails.USER_FORGOT_PASSWORD_BODY
FORGOT_PASSWORD_SUBJECT = 'Password Reset / Επαναφορά κωδικού'

# # reCAPTCHA settings
# RECAPTCHA_PUBLIC_KEY = os.environ.get('RECAPTCHA_PUBLIC_KEY')
# RECAPTCHA_PRIVATE_KEY = os.environ.get('RECAPTCHA_PRIVATE_KEY')

# Settings for reference letter invitations
INVITATION_REFERENCE_MAX_AGE = 30 # Number of days that the invitation links are valid
INVITATION_REFERENCE_MAX_AGE_SECS = INVITATION_REFERENCE_MAX_AGE * 24 * 60 * 60

# Validity period for application confirmation links
APPLICATION_MAX_AGE_DAYS = 7 # Number of days that the application links are valid
APPLICATION_MAX_AGE_SECS = APPLICATION_MAX_AGE_DAYS * 24 * 60 * 60

# Reset password
PASSWORD_RESET_LINK_AGE = 3600

# Development server keywords
DEV_SERVER_KEYWORDS = ['dev', 'localhost', '127.0.0.1']

# CELERY_BROKER_URL = "redis://redis:6379/0"
CELERY_BROKER_URL = "redis://localhost:6379/0"
CELERY_TASK_TRACK_STARTED = True
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_BACKEND = "django-db"

# Budibase key used for migrations:
BUDI_KEY = os.environ.get('BUDI_KEY')
