# Generated by Django 5.2.12 on 2026-08-22 13:18

import accounts.directories
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bodyapplications', '0001_initial'),
        ('subjects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='Δημιουργήθηκε στις')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Ενημερώθηκε στις')),
                ('name', models.CharField(max_length=100, verbose_name='Όνομα Αρχείου')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Δημιουργήθηκε από')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Ενημερώθηκε από')),
            ],
            options={
                'verbose_name': 'Επισυναπτόμενο',
                'verbose_name_plural': 'Επισυναπτόμενα',
            },
        ),
        migrations.CreateModel(
            name='ApplicationAttachment',
            fields=[
                ('attachment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='attachments.attachment')),
                ('file', models.FileField(upload_to=accounts.directories.application_attachment_dir)),
                ('application', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='bodyapplications.application', verbose_name='Αίτηση')),
            ],
            options={
                'verbose_name': 'Επισυναπτόμενο Αίτησης',
                'verbose_name_plural': 'Επισυναπτόμενα Αιτήσεων',
            },
            bases=('attachments.attachment',),
        ),
        migrations.CreateModel(
            name='DecisionAttachment',
            fields=[
                ('attachment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='attachments.attachment')),
                ('file', models.FileField(upload_to=accounts.directories.decision_attachment_dir)),
                ('decision', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='subjects.decision', verbose_name='Απόφαση')),
            ],
            options={
                'verbose_name': 'Επισυναπτόμενο Απόφασης',
                'verbose_name_plural': 'Επισυναπτόμενα Αποφάσεων',
            },
            bases=('attachments.attachment',),
        ),
        migrations.CreateModel(
            name='SubjectAttachment',
            fields=[
                ('attachment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='attachments.attachment')),
                ('file', models.FileField(upload_to=accounts.directories.subject_attachment_dir, verbose_name='Αρχείο')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='subjects.subject', verbose_name='Θέμα')),
            ],
            options={
                'verbose_name': 'Επισυναπτόμενο Θέματος',
                'verbose_name_plural': 'Επισυναπτόμενα Θεμάτων',
            },
            bases=('attachments.attachment',),
        ),
    ]
