# Generated by Django 5.2.12 on 2026-07-14 14:56

import django.db.models.deletion
from django.db import migrations, models

from attachments.models import subject_attachment_upload_to, decision_attachment_upload_to


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to=subject_attachment_upload_to)),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='subjects.subject')),
            ],
            options={
                'verbose_name': 'Επισυναπτόμενο Θέματος',
                'verbose_name_plural': 'Επισυναπτόμενα Θεμάτων',
            },
        ),
        migrations.CreateModel(
            name='DecisionAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to=decision_attachment_upload_to)),
                ('decision', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='subjects.decision')),
            ],
            options={
                'verbose_name': 'Επισυναπτόμενο Απόφασης',
                'verbose_name_plural': 'Επισυναπτόμενα Αποφάσεων',
            },
        ),
    ]
